# Generated by Django 4.1.4 on 2022-12-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('allergens', models.ManyToManyField(to='dictionary.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Животное содержащее Аллерген',
                'verbose_name_plural': 'Животные содержащие Аллерген',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('allergens', models.ManyToManyField(to='dictionary.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Продукт питания',
                'verbose_name_plural': 'Продукты питания',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('allergens', models.ManyToManyField(to='dictionary.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='MyAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_animals', models.ManyToManyField(blank=True, related_name='animals', to='dictionary.animal', verbose_name='Животные Моей Аллергии')),
                ('user_plants', models.ManyToManyField(blank=True, related_name='plants', to='dictionary.plant', verbose_name='Растения содержащие Аллерген')),
                ('user_products', models.ManyToManyField(blank=True, related_name='products', to='dictionary.product', verbose_name='Продукт питания Моей Аллергии')),
            ],
            options={
                'verbose_name': 'Моя Аллергия',
                'verbose_name_plural': 'Мои Аллергии',
            },
        ),
    ]
