# Generated by Django 4.1.4 on 2022-12-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myallergy',
            options={'verbose_name': 'Моя Аллергия', 'verbose_name_plural': 'Карточки Аллергии'},
        ),
    ]
